version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: